server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri =404;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type" always;
    }

    location ~* \.json$ {
        default_type application/json;
        try_files $uri =404;
        add_header Access-Control-Allow-Origin "*" always;
    }

    location ~* \.js$ {
        default_type application/javascript;
        try_files $uri =404;
        add_header Access-Control-Allow-Origin "*" always;
    }

    location ~* \.svg$ {
        default_type image/svg+xml;
        try_files $uri =404;
        add_header Access-Control-Allow-Origin "*" always;
    }

    location ~* \.css$ {
        default_type text/css;
        try_files $uri =404;
        add_header Access-Control-Allow-Origin "*" always;
    }

    if ($request_method = OPTIONS) {
        return 204;
    }
}
